### ISSUE TITLE
pip package not found

### ISSUE THREAD

**Issue by mwang87** [LeidelLab/SMITER#2]

**Comment by MKoesters** [comment]
Hi,

I'm currently setting up the whole CI/CD pipeline.
When this is done, SMITER will be automatically uploaded to pypi as soon as a release is published

Best,
Manuel

**Comment by MKoesters** [comment]
Hi @mwang87,

I uploaded the package now, so its easier available even if continuous deployment is not working yet.

Best,
Manuel
